# fly.toml app configuration file generated for flame-remix on 2024-04-29T12:19:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flame-remix'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
